name: Ci

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install str
        run: |
          pwd
          bark
          git clone https://github.com/soenkehahn/str.git
          just str/install
          just str/typescript-library-bundle

      - uses: actions/checkout@v2

      - name: Ci
        run: |
          yarn remove str
          yarn add link:str/typescript-library
          just ci

      - name: Bundle
        run: just bundle

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
